### ISSUE TITLE
Enabling SIMD WASM on Firefox gets a CompileError

### ISSUE THREAD

**Issue by palfrey** [Ameobea/web-synth#10]
It worked fine in Firefox with the SIMD support off, but switching it on got me `CompileError: wasm validation error: at offset 6424: unrecognized opcode: fd 12` in the console.

Firefox version is 86.0.1 on macOS

**Comment by Ameobea** [comment]
Interesting, idk why that's happening.  I can repro this as well on Firefox Nightly.  The error I'm seeing is slightly different, though: `CompileError: wasm validation error: at offset 46: v128 not enabled`

Reading the firefox source code, it seems to me like that only happens if SIMD isn't enabled.  I've run into this with Firefox in the past with `AudioWorkletProcessor` where they had a feature flag for it in their config but then they had code that basically just always threw an error when one was used.  Perhaps this is what's going on.

I'd have to look up some discussions or mailing lists to see what the actual status of Wasm SIMD in Firefox is.  If they have real support and it works for other use cases but just not this one, perhaps there's a bug that should be reported to them.

**Comment by Ameobea** [comment]
Wasm SIMD has finally had a stable release in the latest chrome and firefox.  I tested again in firefox 89 and it works out of the box without changing any settings!
